In [2]:
import numpy as np

In [4]:
#load data from file into numpy array
n1 = np.loadtxt('/home/bloombench/Documents/PythonPrograms/m_matrix',delimiter=',')
print(n1)
print(type(n1))
print(n1.ndim)
print(n1.shape)

[[ 3.  4.  5.]
 [ 6.  7.  8.]
 [ 9.  4.  2.]]
<class 'numpy.ndarray'>
2
(3, 3)


In [6]:
n2= np.loadtxt('/home/bloombench/Documents/PythonPrograms/n_matrix',delimiter=',')
print(n2)
print(type(n2))
print(n2.ndim)
print(n2.shape)

[[ 1.  1.  2.]
 [ 3.  2.  4.]
 [ 5.  6.  7.]]
<class 'numpy.ndarray'>
2
(3, 3)


In [7]:
n1 + n2

array([[  4.,   5.,   7.],
       [  9.,   9.,  12.],
       [ 14.,  10.,   9.]])

In [9]:
n3 = np.dot(n1,n2) # matrix multiplication
n3

array([[ 40.,  41.,  57.],
       [ 67.,  68.,  96.],
       [ 31.,  29.,  48.]])

In [13]:
np.save('/home/bloombench/Documents/PythonPrograms/output',n3) # save in compressed binary form

In [14]:
n4 = np.load('/home/bloombench/Documents/PythonPrograms/output.npy') # load from binary
n4

array([[ 40.,  41.,  57.],
       [ 67.,  68.,  96.],
       [ 31.,  29.,  48.]])

In [25]:
marks = np.loadtxt('/home/bloombench/Documents/PythonPrograms/marks',delimiter=',')
print(marks)

[[ 50.  70.  40.]
 [ 90.  34.  70.]
 [ 45.  67.  89.]]


In [3]:
correction = np.loadtxt('/home/bloombench/Documents/PythonPrograms/correction_to_add',delimiter=',')
correction

array([  1.,   0.,  10.,   5.,   6.,   8.,   0.,  10.,   8.])

In [27]:
new_marks = (marks.flatten() + correction).reshape(3,3) # flatten-`converts n dimension to 1 dimension
new_marks

array([[ 51.,  70.,  50.],
       [ 95.,  40.,  78.],
       [ 45.,  77.,  97.]])

In [26]:
correction.reshape(3,3)+marks

array([[ 51.,  70.,  50.],
       [ 95.,  40.,  78.],
       [ 45.,  77.,  97.]])