In [1]:
import numpy as np

In [2]:
l = [5, 6, 2, 3]
n1 = np.array(l)
print(type(n1))
print(n1)

<class 'numpy.ndarray'>
[5 6 2 3]


In [3]:
nn1 = n1 + 2
print(nn1)

[7 8 4 5]


In [4]:
l1 = [4.5, 3.2, 5, 7, 3.4]
n2 = np.array(l1)
n2

array([ 4.5,  3.2,  5. ,  7. ,  3.4])

In [5]:
n2.dtype

dtype('float64')

In [6]:
n1.dtype

dtype('int64')

In [7]:
n3 = np.array(['abc', 'def', 'ghi', 'jkl'])
print(n3)
print(n3.dtype)

['abc' 'def' 'ghi' 'jkl']
<U3


In [8]:
# scalar as a numpy array
n4 = np.array(45)
print(n4)
print(n4.dtype)
print(n4.ndim)

45
int64
0


In [10]:
# 1 d array
n5 = np.array([34, 50, 70,100,70,50,78])
print(n5)
print(n5.ndim)
print(n5.shape)

[ 34  50  70 100  70  50  78]
1
(7,)


In [11]:
# 2 d array
n6 = np.array([
    [1,2,3],
    [4,5,6]
])
print(n6)
print(n6.ndim)
print(n6.shape)

[[1 2 3]
 [4 5 6]]
2
(2, 3)


In [12]:
# 3 d array
n7 = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [11,12,13,14],
        [15,16,17,18]
    ]
])
print(n7)
print(n7.ndim)
print(n7.shape)

[[[ 1  2  3  4]
  [ 5  6  7  8]]

 [[11 12 13 14]
  [15 16 17 18]]]
3
(2, 2, 4)


In [13]:
n7 ** 2 # vectorized squaring

array([[[  1,   4,   9,  16],
        [ 25,  36,  49,  64]],

       [[121, 144, 169, 196],
        [225, 256, 289, 324]]])

In [14]:
n8 = np.arange(1,21)
print(n8)
print(type(n8))
print(n8.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
<class 'numpy.ndarray'>
1


In [15]:
n9 = np.arange(30)
print(n9)
print(n9.ndim)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25 26 27 28 29]
1


In [16]:
n8.shape

(20,)

In [17]:
n8.shape = (5,4)
print(n8)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


In [19]:
n9 = np.arange(0,50,7)
print(n9)

[ 0  7 14 21 28 35 42 49]


In [20]:
n10 = np.linspace(0,30,20)
print(n10)

[  0.           1.57894737   3.15789474   4.73684211   6.31578947
   7.89473684   9.47368421  11.05263158  12.63157895  14.21052632
  15.78947368  17.36842105  18.94736842  20.52631579  22.10526316
  23.68421053  25.26315789  26.84210526  28.42105263  30.        ]


In [21]:
n11 = np.linspace(0,30,10)
print(n11)

[  0.           3.33333333   6.66666667  10.          13.33333333
  16.66666667  20.          23.33333333  26.66666667  30.        ]


In [22]:
n11.shape = (5,2)
print(n11)

[[  0.           3.33333333]
 [  6.66666667  10.        ]
 [ 13.33333333  16.66666667]
 [ 20.          23.33333333]
 [ 26.66666667  30.        ]]


In [23]:
n12, stepsize = np.linspace(0,30,25,retstep=True)
print(n12)
print(stepsize)

[  0.     1.25   2.5    3.75   5.     6.25   7.5    8.75  10.    11.25
  12.5   13.75  15.    16.25  17.5   18.75  20.    21.25  22.5   23.75  25.
  26.25  27.5   28.75  30.  ]
1.25


In [24]:
n13 = np.ones((3,3))
print(n13)

[[ 1.  1.  1.]
 [ 1.  1.  1.]
 [ 1.  1.  1.]]


In [25]:
n14 = np.zeros((6,3))
print(n14)

[[ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [26]:
n15 = np.identity(3)
print(n15)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [29]:
n16 = np.eye(4,3)
print(n16)

[[ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]]


In [30]:
n16 = np.eye(4,3,1)
print(n16)

[[ 0.  1.  0.]
 [ 0.  0.  1.]
 [ 0.  0.  0.]
 [ 0.  0.  0.]]


In [31]:
n16 = np.eye(4,3,-1)
print(n16)

[[ 0.  0.  0.]
 [ 1.  0.  0.]
 [ 0.  1.  0.]
 [ 0.  0.  1.]]


In [32]:
n17 = np.array([5,7,2,3,7,8])
print(type(n17))

<class 'numpy.ndarray'>


In [34]:
n17[4]

7

In [35]:
n17[-1]

8

In [38]:
n18 = np.array([
    [1,2,3],
    [4,5,6]
])

In [40]:
n18[1,1]

5

In [41]:
n19 = np.array([
    [
        [1,2,3,4],
        [5,6,7,8]
    ],
    [
        [11,12,13,14],
        [15,16,17,18]
    ]
])
n19[1,0,2]

13

In [42]:
n17

array([5, 7, 2, 3, 7, 8])

In [44]:
n17[2:5]

array([2, 3, 7])

In [45]:
n18

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
n19 = np.array([
    [1,2,3],
    [4,5,6],
    [7,8,9]
])
print(n19)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [47]:
n19[1:,1:]

array([[5, 6],
       [8, 9]])

In [48]:
n19[0:2,1:]

array([[2, 3],
       [5, 6]])

In [49]:
n19[:,2:]

array([[3],
       [6],
       [9]])

In [50]:
n19[:2,:2]

array([[1, 2],
       [4, 5]])

In [51]:
n20 = np.array([
    [
        [1,2,3,4,5],
        [5,6,7,8,3]
    ],
    [
        [11,12,13,14,9],
        [15,16,17,18,2]
    ]
])

print(n20.ndim)

3


In [52]:
n20[1:,:,2:]

array([[[13, 14,  9],
        [17, 18,  2]]])

In [53]:
n20[1:,:,2:] = 0 # slice replacement
n20

array([[[ 1,  2,  3,  4,  5],
        [ 5,  6,  7,  8,  3]],

       [[11, 12,  0,  0,  0],
        [15, 16,  0,  0,  0]]])