In [1]:
import numpy as np

In [2]:
n1 = np.arange(0,9).reshape(3,3)
n1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [3]:
n2 = np.arange(21,30).reshape(3,3)
n2

array([[21, 22, 23],
       [24, 25, 26],
       [27, 28, 29]])

In [4]:
n3 = n1 + n2
n3

array([[21, 23, 25],
       [27, 29, 31],
       [33, 35, 37]])

In [5]:
n1 * n2 # element by element multiplication not matrix multiplication

array([[  0,  22,  46],
       [ 72, 100, 130],
       [162, 196, 232]])

In [6]:
n4 = n1 - n2
n4 = n4 * -1
n4

array([[21, 21, 21],
       [21, 21, 21],
       [21, 21, 21]])

In [7]:
n5 = n1 ** 2
n5

array([[ 0,  1,  4],
       [ 9, 16, 25],
       [36, 49, 64]])

In [9]:
n6 = np.sqrt(n5)
n6

array([[ 0.,  1.,  2.],
       [ 3.,  4.,  5.],
       [ 6.,  7.,  8.]])

In [11]:
n4 = n1 - n2
n4 = np.absolute(n4)
n4

array([[21, 21, 21],
       [21, 21, 21],
       [21, 21, 21]])

In [12]:
n7 = np.array([
    [-2,3],
    [-5,-7]
])
print(n7)

[[-2  3]
 [-5 -7]]


In [14]:
n7[n7<0] = 0 # boolean replacement
n7

array([[0, 3],
       [0, 0]])

In [15]:
# array of marks and another array stores marks
# get the name of student who have scored 100

marks = np.array([56,70,100,34,100,100,89,100,45])
names = np.array(['a','b','c','d','e','f','g','h','i'])

names[marks==100]

array(['c', 'e', 'f', 'h'], 
      dtype='<U1')

In [16]:
np.mean(marks[marks!=100])

58.799999999999997

In [17]:
np.std(marks[marks!=100])

19.239542614105979

In [21]:
names[marks == np.median(marks)]

array(['g'], 
      dtype='<U1')