In [1]:
import numpy as np

In [6]:
data_type = np.dtype([('Name','U20'),('Physics',np.float16),('Chemistry',np.float16),('Maths',np.float16)])

In [7]:
n1 = np.loadtxt('/home/bloombench/Documents/PythonPrograms/student_marks',dtype=data_type,delimiter=',')
n1

array([("b'abc'",  94.,   93.,  97.), ("b'def'",  90.,   92.,  95.),
       ("b'ghi'",  99.,  100.,  93.), ("b'jkl'",  96.,   87.,  90.),
       ("b'mno'",  80.,   78.,  89.)], 
      dtype=[('Name', '<U20'), ('Physics', '<f2'), ('Chemistry', '<f2'), ('Maths', '<f2')])

In [8]:
n1['Physics']

array([ 94.,  90.,  99.,  96.,  80.], dtype=float16)

In [9]:
n1['Physics'][0:2]

array([ 94.,  90.], dtype=float16)

In [10]:
np.average(n1['Physics'])

91.812

In [21]:
total_marks = n1['Physics']+n1['Chemistry']+n1['Maths']
total_marks

array([ 284.,  277.,  292.,  273.,  247.], dtype=float16)

In [23]:
n1['Name']

array(["b'abc'", "b'def'", "b'ghi'", "b'jkl'", "b'mno'"], 
      dtype='<U20')

In [24]:
np.savez('/home/bloombench/Documents/PythonPrograms/student_total_marks',a=n1['Name'],b=total_marks)

In [25]:
ab = np.load('/home/bloombench/Documents/PythonPrograms/student_total_marks.npz')

print(ab['a'])
print(ab['b'])

["b'abc'" "b'def'" "b'ghi'" "b'jkl'" "b'mno'"]
[ 284.  277.  292.  273.  247.]
